### PR TITLE
fix RadioFM and BT headset

### PR DESCRIPTION
**Pull request by mparus**
Change-Id: If063f58e12acee365e606d2e5bc5f14a77e14e80

### CODE REVIEW

**Comment by mparus** [comment]
BT sometimes is good
```
06-13 16:23:46.927  1123  1816 I Telecom : BluetoothRouteManager: No device with address null available. Using 30:A8:DB:F0:1F:96 instead.: PCR.oR->CAMSM.pM_2001->CARSM.pM_SWITCH_FOCUS->BRM.pM_100@FIU
06-13 16:23:46.942  1123  1123 I Telecom : BluetoothRouteManager: Device 30:A8:DB:F0:1F:96 transitioned to audio state 11: BRM.oR@FIc
06-13 16:23:47.521  1123  1123 I Telecom : BluetoothRouteManager: Device 30:A8:DB:F0:1F:96 transitioned to audio state 12: BRM.oR@FJ8
06-13 16:23:47.521  1123  1816 I Telecom : BluetoothRouteManager: Message received: HFP_IS_ON.: BRM.oR->BRM.pM_200@FJ8
06-13 16:23:47.521  1123  1816 I Telecom : BluetoothRouteManager: HFP connection success for device 30:A8:DB:F0:1F:96.: BRM.oR->BRM.pM_200@FJ8

```
but sometimes no
```
06-14 08:59:47.594  1097  1806 I Telecom : BluetoothRouteManager: No device with address null available. Using 30:A8:DB:F0:1F:96 instead.: PCR.oR->CAMSM.pM_2001->CARSM.pM_SWITCH_FOCUS->BRM.pM_100@B+0
06-14 08:59:47.639  1097  1097 I Telecom : BluetoothRouteManager: Device 30:A8:DB:F0:1F:96 transitioned to audio state 11: BRM.oR@B/E
06-14 08:59:52.602  1097  1806 I Telecom : BluetoothRouteManager: Message received: CONNECTION_TIMEOUT.: PCR.oR->CAMSM.pM_2001->CARSM.pM_SWITCH_FOCUS->BRM.pM_100->BRM.pM_300@B+0
06-14 08:59:52.603  1097  1806 I Telecom : BluetoothRouteManager: Connection with device 30:A8:DB:F0:1F:96 timed out.: PCR.oR->CAMSM.pM_2001->CARSM.pM_SWITCH_FOCUS->BRM.pM_100->BRM.pM_300@B+0

```

**Comment by TingyiChen** [comment]
Hmm will check source a2dp config later... Strange

**Comment by mparus** [comment]
Probably this commit fix BT headset problem - I test it from the morning and it's ok
repo android_device_xiaomi_msm8937-common
```
diff --git a/bluetooth/bdroid_buildcfg.h b/bluetooth/bdroid_buildcfg.h
index 2ce5386..417db13 100644
--- a/bluetooth/bdroid_buildcfg.h
+++ b/bluetooth/bdroid_buildcfg.h
@@ -1,6 +1,5 @@
-/**
- * Copyright (C) 2012 The Android Open Source Project
- * Copyright (C) 2016 The CyanogenMod Project
+/*
+ * Copyright (C) 2015 The CyanogenMod Project
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
@@ -18,15 +17,21 @@
 #ifndef _BDROID_BUILDCFG_H
 #define _BDROID_BUILDCFG_H

-#define BTA_SKIP_BLE_READ_REMOTE_FEAT FALSE
-#define MAX_ACL_CONNECTIONS    7
+// Disables read remote device feature
+#define MAX_ACL_CONNECTIONS   16
 #define MAX_L2CAP_CHANNELS    16
 #define BLE_VND_INCLUDED   TRUE
-#define BTA_BLE_SKIP_CONN_UPD  FALSE
-#define BLE_PERIPHERAL_ADV_NAME  FALSE
+
+// skips conn update at conn completion
 #define BT_CLEAN_TURN_ON_DISABLED 1
-#define BTA_DISABLE_DELAY 1000
-#define BTM_SCO_ENHANCED_SYNC_DISABLED TRUE
+#define BTM_SCO_ENHANCED_SYNC_ENABLED FALSE
+
 #define BTM_WBS_INCLUDED TRUE
 #define BTIF_HF_WBS_PREFERRED TRUE
+
+/* Increasing SEPs to 12 from 6 to support SHO/MCast i.e. two streams per codec */
+#define AVDT_NUM_SEPS 12
+
+/* Enable HFP WBS feature */
+#define BTIF_HF_CLIENT_WBS_INCLUDED TRUE
 #endif
```

**Comment by TingyiChen** [comment]
Will test tomorrow..These days busy for school..

**Comment by TingyiChen** [comment]
Update bdroid is a better way to fix bt

**Comment by mparus** [comment]
ok, this fix work - I leave it just in case

**Comment by darshan1205** [comment]
Just header needs update for this change I04c73d723d50c2f619102e1904b05937a77d0103

**Comment by TingyiChen** [comment]
Branch need switch later

**Comment by darshan1205** [comment]
Anyway this PR isn't going in

**Comment by TingyiChen** [comment]
check lineage-15.1 branch and try if bluetooth fixed

**Comment by mparus** [comment]
sorry BT headset not working in today builds lineage-15.1 branch :(
I add this commits https://github.com/mparus/android_device_xiaomi_msm8937-common/commit/8f355d5c6b7d96ec9f370397e213d3b12f69da34 and its ok.

**Comment by TingyiChen** [comment]
check 0616 build on my afh...Seems I forgot to push change

**Comment by TingyiChen** [comment]
SO does this means only a2dp split can make Bluetooth work? bdroid config update can't work?

**Comment by mparus** [comment]
Probably yes, the last your commit in my rom build is https://github.com/HyperTeam/android_device_xiaomi_msm8937-common/commit/3fd9b654ab0322f1757c20538a383a70ecef21b5

**Pull request closed without merging**
